// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1doObPIsm9MWOeGPyAJLsyoyJkRLw8uA',
    appId: '1:96477885413:web:8fc1690159ea9c7519b50c',
    messagingSenderId: '96477885413',
    projectId: 'kursuch-8d665',
    authDomain: 'kursuch-8d665.firebaseapp.com',
    storageBucket: 'kursuch-8d665.appspot.com',
    measurementId: 'G-CMWB7DDT2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB7QTAcIEtsCPklE_UHifJhaaPK7aOGYY',
    appId: '1:96477885413:android:85622dd333c4429319b50c',
    messagingSenderId: '96477885413',
    projectId: 'kursuch-8d665',
    storageBucket: 'kursuch-8d665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDapyd-9Bf2li9fB3XgUPqEUUew0imtJcs',
    appId: '1:96477885413:ios:4c4d58869a5e7c1d19b50c',
    messagingSenderId: '96477885413',
    projectId: 'kursuch-8d665',
    storageBucket: 'kursuch-8d665.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1doObPIsm9MWOeGPyAJLsyoyJkRLw8uA',
    appId: '1:96477885413:web:6d6dbaa2c336698619b50c',
    messagingSenderId: '96477885413',
    projectId: 'kursuch-8d665',
    authDomain: 'kursuch-8d665.firebaseapp.com',
    storageBucket: 'kursuch-8d665.appspot.com',
    measurementId: 'G-GV4ZJLXNWD',
  );

}